# install.ps1 - register this repo\s deploy/windows boot chain on this machine.
# It writes ONE machine-local file - the logon Startup VBS - that points the
# boot chain at this repo\s deploy/windows/dsh-autostart.cmd. Everything else
# the boot runs (dsh-autostart.cmd, dsh-web-update.ps1, dsh-web-plugin-
# compat-check.mjs) is read straight from the repo at logon, so a plain
# `git pull` ships boot-logic changes - no re-copy step.
#
# Run after cloning/moving the repo, or to refresh the Startup entry:
#   powershell -NoProfile -ExecutionPolicy Bypass -File deploy/windows/install.ps1
$ErrorActionPreference = 'Stop'

$winDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$cmd    = Join-Path $winDir 'dsh-autostart.cmd'
if (-not (Test-Path $cmd)) { throw "repo boot launcher not found: $cmd" }

$startup = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
New-Item -ItemType Directory -Force -Path $startup | Out-Null
$vbs = Join-Path $startup 'dsh-web-autostart.vbs'

$lines = @(
  "' Auto-start official DeepSeek Harness Web UI at logon."
  "' Generated by deploy/windows/install.ps1. Runs the boot launcher from the"
  "' repo checkout directly, so `git pull` on this machine ships new boot logic."
  "' Re-run install.ps1 after cloning/moving the repo to refresh this path."
  'Set sh = CreateObject("WScript.Shell")'
  'sh.Run "__CMD__", 0, False'
  'Set sh = Nothing'
)
$content = ($lines -join [Environment]::NewLine).Replace('"__CMD__"', '"""' + $cmd + '"""')
Set-Content -Path $vbs -Value $content -Encoding ASCII
Write-Host "Startup boot entry written: $vbs"
Write-Host "  -> runs $cmd"

# Remove the OLD detached copies (pre-repo-direct install) so only one source
# of truth remains. No-ops if already gone.
$homeDir = $env:USERPROFILE
$stale = @(
  (Join-Path $homeDir '.dsh\bin\dsh-web-update.ps1')
  (Join-Path $homeDir '.dsh\bin\dsh-web-plugin-compat-check.mjs')
  (Join-Path $homeDir '.dsh\dsh-autostart.cmd')
)
foreach ($f in $stale) {
  if (Test-Path $f) { Remove-Item $f -Force; Write-Host "removed stale detached copy: $f" }
}
Write-Host 'Boot now reads the repo deploy/windows files directly.'
